stages:
  - install
  - test
  - build
  - publish

cache:
  paths:
    - node_modules/

Install:
  stage: install
  tags:
    - npm
  script: yarn install --prefer-offline

Test:
  stage: test
  tags:
    - npm
  script: yarn test

Build:
  stage: build
  tags:
    - npm
  script: yarn build

Deploy:
  only:
    - /^v.*$/
  except:
    - branches
  stage: deploy
  tags:
    - npm
  script: npm publish



