stages:
  - install
  - test
  - build
  - publish

cache:
  paths:
    - node_modules/

Install:
  stage: install
  tags:
    - frontend
  script: yarn install --prefer-offline

Test:
  stage: test
  tags:
    - frontend
  script: yarn test

Build:
  stage: build
  tags:
    - frontend
  script: yarn build

Deploy:
  stage: deploy
  tags:
    - frontend


